# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login_menu(object):
    def setupUi(self, login_menu):
        login_menu.setObjectName("login_menu")
        login_menu.resize(418, 518)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        login_menu.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(login_menu)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(login_menu)
        self.scrollArea.setMinimumSize(QtCore.QSize(400, 500))
        self.scrollArea.setMaximumSize(QtCore.QSize(400, 500))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 398, 498))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.username_box = QtWidgets.QLineEdit(self.frame)
        self.username_box.setGeometry(QtCore.QRect(150, 200, 150, 27))
        self.username_box.setObjectName("username_box")
        self.password_box = QtWidgets.QLineEdit(self.frame)
        self.password_box.setGeometry(QtCore.QRect(150, 240, 150, 27))
        self.password_box.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_box.setObjectName("password_box")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 200, 81, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(70, 240, 81, 31))
        self.label_2.setObjectName("label_2")
        self.login_button = QtWidgets.QPushButton(self.frame)
        self.login_button.setGeometry(QtCore.QRect(210, 300, 91, 41))
        self.login_button.setObjectName("login_button")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(80, 390, 150, 20))
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setObjectName("label_3")
        self.register_button = QtWidgets.QLabel(self.frame)
        self.register_button.setGeometry(QtCore.QRect(235, 390, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.register_button.setFont(font)
        self.register_button.setObjectName("register_button")
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(login_menu)
        QtCore.QMetaObject.connectSlotsByName(login_menu)

    def retranslateUi(self, login_menu):
        _translate = QtCore.QCoreApplication.translate
        login_menu.setWindowTitle(_translate("login_menu", "Login"))
        self.label.setText(_translate("login_menu", "Username"))
        self.label_2.setText(_translate("login_menu", "Password"))
        self.login_button.setText(_translate("login_menu", "Login"))
        self.label_3.setText(_translate("login_menu", "Don\'t have account?"))
        self.register_button.setText(_translate("login_menu", "Click Here"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login_menu = QtWidgets.QWidget()
    ui = Ui_login_menu()
    ui.setupUi(login_menu)
    login_menu.show()
    sys.exit(app.exec_())
